import type { BriefingPdfLabels } from '../../domain/stageBriefing.ts'
import type { StageCategory } from '../../domain/models.ts'

export type MatchBriefingsPdfLocale = 'uk' | 'en'

export type MatchBriefingsPdfStrings = {
  titlePageHeading: string
  titleDate: string
  titleLocation: string
  sectionProgrammeStats: string
  sectionParticipants: string
  sectionByDivision: string
  sectionByCategory: string
  colStage: string
  colType: string
  colPaper: string
  colMetal: string
  colCeramic: string
  colPopper: string
  colMini: string
  colAmmo: string
  colShots: string
  colPoints: string
  colPercent: string
  colGroup: string
  colConfirmed: string
  colPending: string
  colTotal: string
  rowTotal: string
  stageViewOnline: string
  emptyCell: string
  briefingLabels: BriefingPdfLabels
  categoryLabel: (c: StageCategory) => string
  generatedFooter: string
}

const UK: MatchBriefingsPdfStrings = {
  titlePageHeading: 'Брифінги матчу',
  titleDate: 'Дата',
  titleLocation: 'Місце',
  sectionProgrammeStats: 'Статистика вправ',
  sectionParticipants: 'Учасники',
  sectionByDivision: 'За дивізіонами',
  sectionByCategory: 'За класами',
  colStage: 'Вправа',
  colType: 'Тип',
  colPaper: 'Папір',
  colMetal: 'Метал',
  colCeramic: 'Кераміка',
  colPopper: 'Попери',
  colMini: 'Міні',
  colAmmo: 'Набої',
  colShots: 'Постріли',
  colPoints: 'Очки',
  colPercent: '% матчу',
  colGroup: 'Група',
  colConfirmed: 'Підтверджені',
  colPending: 'Очікує',
  colTotal: 'Разом',
  rowTotal: 'Разом',
  stageViewOnline: 'Схема онлайн',
  emptyCell: '—',
  briefingLabels: {
    exerciseTypeAndShots: 'Тип вправи · Рекомендовані постріли',
    exerciseTypeAndScoringShots: 'Тип вправи · Залікові постріли',
    exerciseType: 'Тип вправи',
    targets: 'Мішені',
    recommendedShots: 'Рекомендована к-сть пострілів',
    scoringShots: 'К-сть залікових пострілів',
    allowedAmmo: 'Дозволені набої',
    maxPoints: 'Макс. очок',
    startSignal: 'Сигнал старту',
    readyCondition: 'Положення готовності',
    startPosition: 'Стартова позиція',
    procedure: 'Порядок виконання',
    safetyAngles: 'Безпекові кути',
  },
  categoryLabel: (c) => {
    if (c === 'short') return 'Коротка'
    if (c === 'medium') return 'Середня'
    return 'Довга'
  },
  generatedFooter: 'Згенеровано Shooters Tools',
}

const EN: MatchBriefingsPdfStrings = {
  titlePageHeading: 'Match briefings',
  titleDate: 'Date',
  titleLocation: 'Location',
  sectionProgrammeStats: 'Stage statistics',
  sectionParticipants: 'Participants',
  sectionByDivision: 'By division',
  sectionByCategory: 'By class',
  colStage: 'Stage',
  colType: 'Type',
  colPaper: 'Paper',
  colMetal: 'Metal',
  colCeramic: 'Ceramic',
  colPopper: 'Poppers',
  colMini: 'Mini',
  colAmmo: 'Ammo',
  colShots: 'Shots',
  colPoints: 'Points',
  colPercent: '% of match',
  colGroup: 'Group',
  colConfirmed: 'Confirmed',
  colPending: 'Pending',
  colTotal: 'Total',
  rowTotal: 'Total',
  stageViewOnline: 'Course of fire online',
  emptyCell: '—',
  briefingLabels: {
    exerciseTypeAndShots: 'Exercise type · Recommended shots',
    exerciseTypeAndScoringShots: 'Exercise type · Rounds to be scored',
    exerciseType: 'Exercise type',
    targets: 'Targets',
    recommendedShots: 'Recommended round count',
    scoringShots: 'Rounds to be scored',
    allowedAmmo: 'Permitted ammunition',
    maxPoints: 'Maximum score',
    startSignal: 'Start signal',
    readyCondition: 'Ready condition',
    startPosition: 'Start position',
    procedure: 'Course of fire',
    safetyAngles: 'Safety angles',
  },
  categoryLabel: (c) => {
    if (c === 'short') return 'Short'
    if (c === 'medium') return 'Medium'
    return 'Long'
  },
  generatedFooter: 'Generated by Shooters Tools',
}

export function matchBriefingsPdfStrings(locale: MatchBriefingsPdfLocale): MatchBriefingsPdfStrings {
  return locale === 'en' ? EN : UK
}
